language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "stable"
services:
  - mongodb
before_install:
  - pip install codecov
after_success:
  - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket  --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
  - codecov