language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "stable"
services:
  - mongodb
before_install:
  - sudo pip install codecov
after_success:
  - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket  --reporter mocha-lcov-reporter > cov
  - cat cov | ./node_modules/coveralls/bin/coveralls.js
  - cat cov | codecov