language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "stable"
before_install:
  - phantomjs --version
services:
  - mongodb
script:
  - npm test
  - npm run karma-single-phantom
after_success:
  - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket  --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
  - istanbul cover node_modules/mocha/bin/_mocha && codecov